services:
  public-transit-service:
    image: ghcr.io/naviqore/public-transit-service:v1.0.0
    ports:
      - "8080:8080"
    environment:
      - GTFS_STATIC_URI=https://developers.google.com/static/transit/gtfs/examples/sample-feed.zip
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health | grep '\"status\":\"UP\"' || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  public-transit-viewer:
    image: ghcr.io/naviqore/public-transit-viewer:v1.0.0
    ports:
      - "8501:8501"
    environment:
      - NAVIQORE_SERVICE_URL=http://public-transit-service:8080
    restart: unless-stopped
    depends_on:
      - public-transit-service
