publicTransitService:
  image:
    repository: ghcr.io/naviqore/public-transit-service
    tag: v1.0.0
  service:
    type: ClusterIP
    port: 8080
  env:
    GTFS_STATIC_URI: https://developers.google.com/static/transit/gtfs/examples/sample-feed.zip

publicTransitViewer:
  image:
    repository: ghcr.io/naviqore/public-transit-viewer
    tag: v1.0.0
  service:
    type: LoadBalancer
    port: 8501
  env:
    NAVIQORE_SERVICE_URL: http://public-transit-service:8080
